<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.edu.lab2</groupId>
    <artifactId>lab2-katas</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>katas/kata1-roman-numerals</module>
        <module>katas/kata2-bowling-game</module>
        <module>katas/kata3-fizzbuzz-custom</module>
        <module>katas/kata4-string-calculator</module>
        <module>katas/kata5-poker-hands</module>
        <module>katas/kata6-luhn-algorithm</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <junit.jupiter.version>5.10.2</junit.jupiter.version>
    </properties>
</project>
